### test 1: Providing header directly
GET http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json
some: header


### test 2
GET http://localhost:4004/odata/v4/catalog/callBooksWithHeader()
Content-Type: application/json

