### Test 1: Providing header directly
GET http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json
some: header


### Test 2: Call function to read the books, while enriching the request with a header paramter
GET http://localhost:4004/odata/v4/catalog/callBooksWithHeader()
Content-Type: application/json

